import { Candidate } from "./types";

export const INITIAL_CANDIDATES: Candidate[] = [
  {
    id: "1",
    name: "Abraham Lincoln",
    category: "Historical",
    image: "https://picsum.photos/seed/lincoln/600/800",
    baseVapeScore: 5,
  },
  {
    id: "2",
    name: "Elon Musk",
    category: "Tech Mogul",
    image: "https://picsum.photos/seed/musk/600/800",
    baseVapeScore: 85,
  },
  {
    id: "3",
    name: "SpongeBob SquarePants",
    category: "Cartoon",
    image: "https://picsum.photos/seed/spongebob/600/800",
    baseVapeScore: 10,
  },
  {
    id: "4",
    name: "Post Malone",
    category: "Musician",
    image: "https://picsum.photos/seed/post/600/800",
    baseVapeScore: 98,
  },
  {
    id: "5",
    name: "Mary Berry",
    category: "Chef",
    image: "https://picsum.photos/seed/berry/600/800",
    baseVapeScore: 2,
  },
  {
    id: "6",
    name: "Batman",
    category: "Superhero",
    image: "https://picsum.photos/seed/batman/600/800",
    baseVapeScore: 40,
  },
  {
    id: "7",
    name: "Shaggy Rogers",
    category: "Cartoon",
    image: "https://picsum.photos/seed/shaggy/600/800",
    baseVapeScore: 92,
  },
  {
    id: "8",
    name: "The Mona Lisa",
    category: "Art",
    image: "https://picsum.photos/seed/monalisa/600/800",
    baseVapeScore: 15,
  },
  {
    id: "9",
    name: "Keanu Reeves",
    category: "Actor",
    image: "https://picsum.photos/seed/keanu/600/800",
    baseVapeScore: 25,
  },
  {
    id: "10",
    name: "Guy Fieri",
    category: "Chef",
    image: "https://picsum.photos/seed/fieri/600/800",
    baseVapeScore: 78,
  },
  // --- 100 more candidates below ---
  {
    id: "11",
    name: "Taylor Swift",
    category: "Musician",
    image: "https://picsum.photos/seed/taylor/600/800",
    baseVapeScore: 30,
  },
  {
    id: "12",
    name: "Albert Einstein",
    category: "Scientist",
    image: "https://picsum.photos/seed/einstein/600/800",
    baseVapeScore: 8,
  },
  {
    id: "13",
    name: "Oprah Winfrey",
    category: "TV Host",
    image: "https://picsum.photos/seed/oprah/600/800",
    baseVapeScore: 12,
  },
  {
    id: "14",
    name: "Dwayne Johnson",
    category: "Actor",
    image: "https://picsum.photos/seed/therock/600/800",
    baseVapeScore: 55,
  },
  {
    id: "15",
    name: "Yoda",
    category: "Fictional",
    image: "https://picsum.photos/seed/yoda/600/800",
    baseVapeScore: 60,
  },
  {
    id: "16",
    name: "Serena Williams",
    category: "Athlete",
    image: "https://picsum.photos/seed/serena/600/800",
    baseVapeScore: 18,
  },
  {
    id: "17",
    name: "Beyoncé",
    category: "Musician",
    image: "https://picsum.photos/seed/beyonce/600/800",
    baseVapeScore: 22,
  },
  {
    id: "18",
    name: "David Attenborough",
    category: "Naturalist",
    image: "https://picsum.photos/seed/attenborough/600/800",
    baseVapeScore: 3,
  },
  {
    id: "19",
    name: "Homer Simpson",
    category: "Cartoon",
    image: "https://picsum.photos/seed/homer/600/800",
    baseVapeScore: 80,
  },
  {
    id: "20",
    name: "Mona the Cat",
    category: "Pet",
    image: "https://picsum.photos/seed/monacat/600/800",
    baseVapeScore: 1,
  },
  {
    id: "21",
    name: "Barack Obama",
    category: "Political",
    image: "https://picsum.photos/seed/obama/600/800",
    baseVapeScore: 20,
  },
  {
    id: "22",
    name: "Vladimir Putin",
    category: "Political",
    image: "https://picsum.photos/seed/putin/600/800",
    baseVapeScore: 15,
  },
  {
    id: "23",
    name: "Ariana Grande",
    category: "Musician",
    image: "https://picsum.photos/seed/ariana/600/800",
    baseVapeScore: 19,
  },
  {
    id: "24",
    name: "Bill Gates",
    category: "Tech Mogul",
    image: "https://picsum.photos/seed/gates/600/800",
    baseVapeScore: 35,
  },
  {
    id: "25",
    name: "Mahatma Gandhi",
    category: "Historical",
    image: "https://picsum.photos/seed/gandhi/600/800",
    baseVapeScore: 2,
  },
  {
    id: "26",
    name: "Wonder Woman",
    category: "Superhero",
    image: "https://picsum.photos/seed/wonderwoman/600/800",
    baseVapeScore: 45,
  },
  {
    id: "27",
    name: "Bob Ross",
    category: "Artist",
    image: "https://picsum.photos/seed/bobross/600/800",
    baseVapeScore: 10,
  },
  {
    id: "28",
    name: "Queen Elizabeth II",
    category: "Royalty",
    image: "https://picsum.photos/seed/queen/600/800",
    baseVapeScore: 4,
  },
  {
    id: "29",
    name: "Mario",
    category: "Video Game",
    image: "https://picsum.photos/seed/mario/600/800",
    baseVapeScore: 50,
  },
  {
    id: "30",
    name: "Luigi",
    category: "Video Game",
    image: "https://picsum.photos/seed/luigi/600/800",
    baseVapeScore: 48,
  },
  {
    id: "31",
    name: "Steve Jobs",
    category: "Tech Mogul",
    image: "https://picsum.photos/seed/jobs/600/800",
    baseVapeScore: 33,
  },
  {
    id: "32",
    name: "Kim Kardashian",
    category: "Celebrity",
    image: "https://picsum.photos/seed/kimk/600/800",
    baseVapeScore: 27,
  },
  {
    id: "33",
    name: "Shrek",
    category: "Fictional",
    image: "https://picsum.photos/seed/shrek/600/800",
    baseVapeScore: 70,
  },
  {
    id: "34",
    name: "Darth Vader",
    category: "Fictional",
    image: "https://picsum.photos/seed/vader/600/800",
    baseVapeScore: 65,
  },
  {
    id: "35",
    name: "Ellen DeGeneres",
    category: "TV Host",
    image: "https://picsum.photos/seed/ellen/600/800",
    baseVapeScore: 13,
  },
  {
    id: "36",
    name: "Morgan Freeman",
    category: "Actor",
    image: "https://picsum.photos/seed/freeman/600/800",
    baseVapeScore: 17,
  },
  {
    id: "37",
    name: "Simone Biles",
    category: "Athlete",
    image: "https://picsum.photos/seed/simone/600/800",
    baseVapeScore: 7,
  },
  {
    id: "38",
    name: "Pikachu",
    category: "Cartoon",
    image: "https://picsum.photos/seed/pikachu/600/800",
    baseVapeScore: 55,
  },
  {
    id: "39",
    name: "Meryl Streep",
    category: "Actor",
    image: "https://picsum.photos/seed/meryl/600/800",
    baseVapeScore: 11,
  },
  {
    id: "40",
    name: "LeBron James",
    category: "Athlete",
    image: "https://picsum.photos/seed/lebron/600/800",
    baseVapeScore: 23,
  },
  {
    id: "41",
    name: "Sonic the Hedgehog",
    category: "Video Game",
    image: "https://picsum.photos/seed/sonic/600/800",
    baseVapeScore: 52,
  },
  {
    id: "42",
    name: "Marge Simpson",
    category: "Cartoon",
    image: "https://picsum.photos/seed/marge/600/800",
    baseVapeScore: 16,
  },
  {
    id: "43",
    name: "Stephen Hawking",
    category: "Scientist",
    image: "https://picsum.photos/seed/hawking/600/800",
    baseVapeScore: 6,
  },
  {
    id: "44",
    name: "Zendaya",
    category: "Actor",
    image: "https://picsum.photos/seed/zendaya/600/800",
    baseVapeScore: 21,
  },
  {
    id: "45",
    name: "Will Smith",
    category: "Actor",
    image: "https://picsum.photos/seed/willsmith/600/800",
    baseVapeScore: 29,
  },
  {
    id: "46",
    name: "Adele",
    category: "Musician",
    image: "https://picsum.photos/seed/adele/600/800",
    baseVapeScore: 14,
  },
  {
    id: "47",
    name: "Tom Hanks",
    category: "Actor",
    image: "https://picsum.photos/seed/hanks/600/800",
    baseVapeScore: 18,
  },
  {
    id: "48",
    name: "Rihanna",
    category: "Musician",
    image: "https://picsum.photos/seed/rihanna/600/800",
    baseVapeScore: 24,
  },
  {
    id: "49",
    name: "Snoop Dogg",
    category: "Musician",
    image: "https://picsum.photos/seed/snoop/600/800",
    baseVapeScore: 99,
  },
  {
    id: "50",
    name: "Mister Rogers",
    category: "TV Host",
    image: "https://picsum.photos/seed/mrrogers/600/800",
    baseVapeScore: 4,
  },
  // ... 60 more ...
  {
    id: "51",
    name: "Gal Gadot",
    category: "Actor",
    image: "https://picsum.photos/seed/gadot/600/800",
    baseVapeScore: 26,
  },
  {
    id: "52",
    name: "Billie Eilish",
    category: "Musician",
    image: "https://picsum.photos/seed/billie/600/800",
    baseVapeScore: 31,
  },
  {
    id: "53",
    name: "Jeff Bezos",
    category: "Tech Mogul",
    image: "https://picsum.photos/seed/bezos/600/800",
    baseVapeScore: 38,
  },
  {
    id: "54",
    name: "Megan Rapinoe",
    category: "Athlete",
    image: "https://picsum.photos/seed/rapinoe/600/800",
    baseVapeScore: 9,
  },
  {
    id: "55",
    name: "Winston Churchill",
    category: "Historical",
    image: "https://picsum.photos/seed/churchill/600/800",
    baseVapeScore: 7,
  },
  {
    id: "56",
    name: "Hermione Granger",
    category: "Fictional",
    image: "https://picsum.photos/seed/hermione/600/800",
    baseVapeScore: 34,
  },
  {
    id: "57",
    name: "Bart Simpson",
    category: "Cartoon",
    image: "https://picsum.photos/seed/bart/600/800",
    baseVapeScore: 77,
  },
  {
    id: "58",
    name: "Queen Latifah",
    category: "Musician",
    image: "https://picsum.photos/seed/latifah/600/800",
    baseVapeScore: 20,
  },
  {
    id: "59",
    name: "Neil Armstrong",
    category: "Astronaut",
    image: "https://picsum.photos/seed/armstrong/600/800",
    baseVapeScore: 8,
  },
  {
    id: "60",
    name: "Mila Kunis",
    category: "Actor",
    image: "https://picsum.photos/seed/kunis/600/800",
    baseVapeScore: 22,
  },
  {
    id: "61",
    name: "Usain Bolt",
    category: "Athlete",
    image: "https://picsum.photos/seed/bolt/600/800",
    baseVapeScore: 12,
  },
  {
    id: "62",
    name: "Emma Watson",
    category: "Actor",
    image: "https://picsum.photos/seed/emma/600/800",
    baseVapeScore: 19,
  },
  {
    id: "63",
    name: "Vin Diesel",
    category: "Actor",
    image: "https://picsum.photos/seed/vin/600/800",
    baseVapeScore: 41,
  },
  {
    id: "64",
    name: "Dua Lipa",
    category: "Musician",
    image: "https://picsum.photos/seed/dua/600/800",
    baseVapeScore: 28,
  },
  {
    id: "65",
    name: "Chris Hemsworth",
    category: "Actor",
    image: "https://picsum.photos/seed/hemsworth/600/800",
    baseVapeScore: 36,
  },
  {
    id: "66",
    name: "Angelina Jolie",
    category: "Actor",
    image: "https://picsum.photos/seed/jolie/600/800",
    baseVapeScore: 32,
  },
  {
    id: "67",
    name: "Lionel Messi",
    category: "Athlete",
    image: "https://picsum.photos/seed/messi/600/800",
    baseVapeScore: 21,
  },
  {
    id: "68",
    name: "Selena Gomez",
    category: "Musician",
    image: "https://picsum.photos/seed/selena/600/800",
    baseVapeScore: 23,
  },
  {
    id: "69",
    name: "Drake",
    category: "Musician",
    image: "https://picsum.photos/seed/drake/600/800",
    baseVapeScore: 44,
  },
  {
    id: "70",
    name: "Scarlett Johansson",
    category: "Actor",
    image: "https://picsum.photos/seed/scarlett/600/800",
    baseVapeScore: 25,
  },
  {
    id: "71",
    name: "Harrison Ford",
    category: "Actor",
    image: "https://picsum.photos/seed/ford/600/800",
    baseVapeScore: 16,
  },
  {
    id: "72",
    name: "Zendaya",
    category: "Actor",
    image: "https://picsum.photos/seed/zendaya2/600/800",
    baseVapeScore: 18,
  },
  {
    id: "73",
    name: "Chris Pratt",
    category: "Actor",
    image: "https://picsum.photos/seed/pratt/600/800",
    baseVapeScore: 27,
  },
  {
    id: "74",
    name: "Ed Sheeran",
    category: "Musician",
    image: "https://picsum.photos/seed/edsheeran/600/800",
    baseVapeScore: 19,
  },
  {
    id: "75",
    name: "Gordon Ramsay",
    category: "Chef",
    image: "https://picsum.photos/seed/ramsay/600/800",
    baseVapeScore: 39,
  },
  {
    id: "76",
    name: "Macaulay Culkin",
    category: "Actor",
    image: "https://picsum.photos/seed/culkin/600/800",
    baseVapeScore: 14,
  },
  {
    id: "77",
    name: "Tyler, The Creator",
    category: "Musician",
    image: "https://picsum.photos/seed/tyler/600/800",
    baseVapeScore: 61,
  },
  {
    id: "78",
    name: "Jack Black",
    category: "Actor",
    image: "https://picsum.photos/seed/jackblack/600/800",
    baseVapeScore: 37,
  },
  {
    id: "79",
    name: "Martha Stewart",
    category: "Chef",
    image: "https://picsum.photos/seed/martha/600/800",
    baseVapeScore: 11,
  },
  {
    id: "80",
    name: "Samuel L. Jackson",
    category: "Actor",
    image: "https://picsum.photos/seed/samuel/600/800",
    baseVapeScore: 35,
  },
  {
    id: "81",
    name: "Dolly Parton",
    category: "Musician",
    image: "https://picsum.photos/seed/dolly/600/800",
    baseVapeScore: 13,
  },
  {
    id: "82",
    name: "Hugh Jackman",
    category: "Actor",
    image: "https://picsum.photos/seed/jackman/600/800",
    baseVapeScore: 24,
  },
  {
    id: "83",
    name: "Oprah Winfrey",
    category: "TV Host",
    image: "https://picsum.photos/seed/oprah2/600/800",
    baseVapeScore: 12,
  },
  {
    id: "84",
    name: "Keira Knightley",
    category: "Actor",
    image: "https://picsum.photos/seed/keira/600/800",
    baseVapeScore: 15,
  },
  {
    id: "85",
    name: "Will Ferrell",
    category: "Actor",
    image: "https://picsum.photos/seed/ferrell/600/800",
    baseVapeScore: 29,
  },
  {
    id: "86",
    name: "Galileo Galilei",
    category: "Scientist",
    image: "https://picsum.photos/seed/galileo/600/800",
    baseVapeScore: 5,
  },
  {
    id: "87",
    name: "Marie Curie",
    category: "Scientist",
    image: "https://picsum.photos/seed/curie/600/800",
    baseVapeScore: 4,
  },
  {
    id: "88",
    name: "Isaac Newton",
    category: "Scientist",
    image: "https://picsum.photos/seed/newton/600/800",
    baseVapeScore: 6,
  },
  {
    id: "89",
    name: "Frida Kahlo",
    category: "Artist",
    image: "https://picsum.photos/seed/frida/600/800",
    baseVapeScore: 8,
  },
  {
    id: "90",
    name: "Vincent van Gogh",
    category: "Artist",
    image: "https://picsum.photos/seed/vangogh/600/800",
    baseVapeScore: 7,
  },
  {
    id: "91",
    name: "Leonardo da Vinci",
    category: "Artist",
    image: "https://picsum.photos/seed/davinci/600/800",
    baseVapeScore: 9,
  },
  {
    id: "92",
    name: "Banksy",
    category: "Artist",
    image: "https://picsum.photos/seed/banksy/600/800",
    baseVapeScore: 20,
  },
  {
    id: "93",
    name: "Pablo Picasso",
    category: "Artist",
    image: "https://picsum.photos/seed/picasso/600/800",
    baseVapeScore: 10,
  },
  {
    id: "94",
    name: "Andy Warhol",
    category: "Artist",
    image: "https://picsum.photos/seed/warhol/600/800",
    baseVapeScore: 12,
  },
  {
    id: "95",
    name: "Salvador Dalí",
    category: "Artist",
    image: "https://picsum.photos/seed/dali/600/800",
    baseVapeScore: 11,
  },
  {
    id: "96",
    name: "Rembrandt",
    category: "Artist",
    image: "https://picsum.photos/seed/rembrandt/600/800",
    baseVapeScore: 8,
  },
  {
    id: "97",
    name: "Claude Monet",
    category: "Artist",
    image: "https://picsum.photos/seed/monet/600/800",
    baseVapeScore: 7,
  },
  {
    id: "98",
    name: "Georgia O’Keeffe",
    category: "Artist",
    image: "https://picsum.photos/seed/okeeffe/600/800",
    baseVapeScore: 6,
  },
  {
    id: "99",
    name: "Henri Matisse",
    category: "Artist",
    image: "https://picsum.photos/seed/matisse/600/800",
    baseVapeScore: 5,
  },
  {
    id: "100",
    name: "Edvard Munch",
    category: "Artist",
    image: "https://picsum.photos/seed/munch/600/800",
    baseVapeScore: 4,
  },
  {
    id: "101",
    name: "J.K. Rowling",
    category: "Author",
    image: "https://picsum.photos/seed/rowling/600/800",
    baseVapeScore: 13,
  },
  {
    id: "102",
    name: "Stephen King",
    category: "Author",
    image: "https://picsum.photos/seed/king/600/800",
    baseVapeScore: 15,
  },
  {
    id: "103",
    name: "Agatha Christie",
    category: "Author",
    image: "https://picsum.photos/seed/christie/600/800",
    baseVapeScore: 8,
  },
  {
    id: "104",
    name: "George R.R. Martin",
    category: "Author",
    image: "https://picsum.photos/seed/grrm/600/800",
    baseVapeScore: 17,
  },
  {
    id: "105",
    name: "J.R.R. Tolkien",
    category: "Author",
    image: "https://picsum.photos/seed/tolkien/600/800",
    baseVapeScore: 10,
  },
  {
    id: "106",
    name: "Mark Twain",
    category: "Author",
    image: "https://picsum.photos/seed/twain/600/800",
    baseVapeScore: 9,
  },
  {
    id: "107",
    name: "Jane Austen",
    category: "Author",
    image: "https://picsum.photos/seed/austen/600/800",
    baseVapeScore: 7,
  },
  {
    id: "108",
    name: "Charles Dickens",
    category: "Author",
    image: "https://picsum.photos/seed/dickens/600/800",
    baseVapeScore: 8,
  },
  {
    id: "109",
    name: "Ernest Hemingway",
    category: "Author",
    image: "https://picsum.photos/seed/hemingway/600/800",
    baseVapeScore: 12,
  },
  {
    id: "110",
    name: "F. Scott Fitzgerald",
    category: "Author",
    image: "https://picsum.photos/seed/fitzgerald/600/800",
    baseVapeScore: 11,
  },
];
